#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.16
# from Racc grammar file "".
#

require 'racc/parser.rb'
class STSParser < Racc::Parser

module_eval(<<'...end sts_parse.ry/module_eval...', 'sts_parse.ry', 103)

def parse( tokens )
  @tokens = tokens

  @yydebug = true
  do_parse()
end

def next_token
  @tokens.shift
end

def on_error(t, val, vstack)
  raise Racc::ParseError, sprintf(
    "Parse error on value %s (%s)\n",
    val.inspect, token_to_str(t) || '?' )
end

...end sts_parse.ry/module_eval...
##### State transition tables begin ###

racc_action_table = [
    56,    50,    86,    57,    58,    59,    60,    61,    62,    63,
    64,    65,    66,    67,    68,    69,    70,    71,    72,    73,
    74,    75,    76,    77,    78,    79,    80,    81,    82,    83,
    84,    56,     4,     5,    57,    58,    59,    60,    61,    62,
    63,    64,    65,    66,    67,    68,    69,    70,    71,    72,
    73,    74,    75,    76,    77,    78,    79,    80,    81,    82,
    83,    84,    30,    11,    11,    12,    12,    14,    13,    13,
    22,    15,    17,    23,    24,    25,    22,    27,    28,    23,
    24,    25,    42,    32,    33,    23,    24,    25,    34,    40,
    40,    45,    40,    32,    47,    40,    50,    51,    52,    85 ]

racc_action_check = [
    50,    52,    52,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    54,     0,     1,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    18,     2,    17,     2,    17,     3,     2,    17,
    18,     5,     6,    18,    18,    18,    11,    12,    13,    11,
    11,    11,    32,    22,    26,    32,    32,    32,    27,    28,
    33,    35,    36,    40,    43,    44,    45,    47,    48,    51 ]

racc_action_pointer = [
    22,    33,    61,    57,   nil,    71,    62,   nil,   nil,   nil,
   nil,    65,    64,    67,   nil,   nil,   nil,    62,    59,   nil,
   nil,   nil,    71,   nil,   nil,   nil,    73,    77,    78,   nil,
   nil,   nil,    71,    79,   nil,    81,    81,   nil,   nil,   nil,
    81,   nil,   nil,    84,    84,    88,   nil,    92,    88,   nil,
   -11,    93,    -7,   nil,    20,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -67,   -71,   -71,   -68,   -70,   -71,   -67,    -3,    -4,    -5,
    -6,   -10,   -15,   -71,   -69,    89,    -1,   -70,   -71,   -11,
   -13,   -14,   -30,   -27,   -28,   -29,   -71,   -71,   -19,    -2,
    -7,   -12,   -71,   -17,   -16,   -71,   -20,   -22,   -23,   -24,
   -25,   -26,   -30,   -71,   -18,   -71,   -21,   -71,   -71,   -32,
   -34,   -71,   -71,   -33,   -35,   -37,   -38,   -39,   -40,   -41,
   -42,   -43,   -44,   -45,   -46,   -47,   -48,   -49,   -50,   -51,
   -52,   -53,   -54,   -55,   -56,   -57,   -58,   -59,   -60,   -61,
   -62,   -63,   -64,   -65,   -66,    -8,    -9,   -31,   -36 ]

racc_goto_table = [
     7,    46,     2,    19,    21,    49,     1,     6,    16,    46,
    31,    21,    87,    36,    18,    29,    55,    26,    44,    43,
    88,    35,    48,    41,    53,    54 ]

racc_goto_check = [
     4,    17,     2,    13,    15,    19,     1,     3,     2,    17,
    13,    15,    19,    16,     8,     4,    22,     9,    16,    10,
    22,    11,    12,    14,    20,    21 ]

racc_goto_pointer = [
   nil,     6,     2,     5,    -2,   nil,   nil,   nil,     3,     5,
   -14,    -7,   -23,    -8,    -9,    -7,   -15,   -35,   nil,   -40,
   -26,   -25,   -34,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     8,     9,    10,   nil,   nil,
   nil,   nil,   nil,   nil,    20,    39,   nil,    37,    38,   nil,
   nil,   nil,   nil,     3 ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 43, :_reduce_1,
  3, 45, :_reduce_2,
  1, 45, :_reduce_3,
  1, 46, :_reduce_4,
  1, 46, :_reduce_5,
  1, 46, :_reduce_6,
  3, 47, :_reduce_7,
  7, 48, :_reduce_8,
  7, 49, :_reduce_9,
  0, 50, :_reduce_10,
  1, 50, :_reduce_11,
  2, 50, :_reduce_12,
  1, 55, :_reduce_13,
  1, 55, :_reduce_14,
  0, 51, :_reduce_15,
  2, 51, :_reduce_16,
  0, 52, :_reduce_17,
  1, 52, :_reduce_18,
  0, 53, :_reduce_19,
  1, 53, :_reduce_20,
  2, 58, :_reduce_21,
  1, 58, :_reduce_22,
  1, 59, :_reduce_23,
  1, 59, :_reduce_24,
  1, 60, :_reduce_25,
  3, 57, :_reduce_26,
  1, 56, :_reduce_27,
  1, 56, :_reduce_28,
  1, 56, :_reduce_29,
  1, 56, :_reduce_30,
  3, 54, :_reduce_31,
  1, 54, :_reduce_32,
  2, 61, :_reduce_33,
  0, 62, :_reduce_34,
  1, 62, :_reduce_35,
  2, 63, :_reduce_36,
  1, 63, :_reduce_37,
  1, 64, :_reduce_38,
  1, 64, :_reduce_39,
  1, 64, :_reduce_40,
  1, 64, :_reduce_41,
  1, 64, :_reduce_42,
  1, 64, :_reduce_43,
  1, 64, :_reduce_44,
  1, 64, :_reduce_45,
  1, 64, :_reduce_46,
  1, 64, :_reduce_47,
  1, 64, :_reduce_48,
  1, 64, :_reduce_49,
  1, 64, :_reduce_50,
  1, 64, :_reduce_51,
  1, 64, :_reduce_52,
  1, 64, :_reduce_53,
  1, 64, :_reduce_54,
  1, 64, :_reduce_55,
  1, 64, :_reduce_56,
  1, 64, :_reduce_57,
  1, 64, :_reduce_58,
  1, 64, :_reduce_59,
  1, 64, :_reduce_60,
  1, 64, :_reduce_61,
  1, 64, :_reduce_62,
  1, 64, :_reduce_63,
  1, 64, :_reduce_64,
  1, 64, :_reduce_65,
  1, 64, :_reduce_66,
  0, 44, :_reduce_none,
  1, 44, :_reduce_none,
  2, 65, :_reduce_none,
  1, 65, :_reduce_none ]

racc_reduce_n = 71

racc_shift_n = 89

racc_token_table = {
  false => 0,
  :error => 1,
  :TOP_INST => 2,
  :TOP_INST_END => 3,
  :DATA_START => 4,
  :DATA_SCRIPT => 5,
  :DATA_END => 6,
  :PROC_START => 7,
  :PROC_INST => 8,
  :PROC_END => 9,
  :TERMIN => 10,
  :IDENT => 11,
  :ASSIGN => 12,
  :COLON => 13,
  :NUMBER => 14,
  :SQ_STRING => 15,
  :DQ_STRING => 16,
  :P_EQ => 17,
  :P_DEQ => 18,
  :P_MULT => 19,
  :P_PLUS => 20,
  :P_MINUS => 21,
  :P_INTDEV => 22,
  :P_MOD => 23,
  :P_IN => 24,
  :P_AND => 25,
  :P_OR => 26,
  :P_DAND => 27,
  :P_DOR => 28,
  :P_LT => 29,
  :P_ST => 30,
  :P_LTE => 31,
  :P_STE => 32,
  :P_HAT => 33,
  :P_TILDE => 34,
  :P_COLON => 35,
  :P_LPAR => 36,
  :P_RPAR => 37,
  :P_LSQBR => 38,
  :P_RSQBR => 39,
  :P_COMMA => 40,
  :P_SLASH => 41 }

racc_nt_base = 42

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TOP_INST",
  "TOP_INST_END",
  "DATA_START",
  "DATA_SCRIPT",
  "DATA_END",
  "PROC_START",
  "PROC_INST",
  "PROC_END",
  "TERMIN",
  "IDENT",
  "ASSIGN",
  "COLON",
  "NUMBER",
  "SQ_STRING",
  "DQ_STRING",
  "P_EQ",
  "P_DEQ",
  "P_MULT",
  "P_PLUS",
  "P_MINUS",
  "P_INTDEV",
  "P_MOD",
  "P_IN",
  "P_AND",
  "P_OR",
  "P_DAND",
  "P_DOR",
  "P_LT",
  "P_ST",
  "P_LTE",
  "P_STE",
  "P_HAT",
  "P_TILDE",
  "P_COLON",
  "P_LPAR",
  "P_RPAR",
  "P_LSQBR",
  "P_RSQBR",
  "P_COMMA",
  "P_SLASH",
  "$start",
  "program",
  "opt_termins",
  "blocks",
  "block",
  "top_stmt",
  "data_block",
  "proc_block",
  "top_options",
  "data_engine_option",
  "data_options",
  "proc_options",
  "proc_stmts",
  "value_or_kv",
  "opt_primary",
  "kv",
  "options",
  "key_or_kv",
  "key",
  "proc_stmt",
  "optional_proc_stmt_options",
  "proc_stmt_options",
  "proc_primary",
  "termins" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'sts_parse.ry', 6)
  def _reduce_1(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 8)
  def _reduce_2(val, _values, result)
     val[0] << val[2] ; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 9)
  def _reduce_3(val, _values, result)
     result = Array.new(1, val[0] )
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 11)
  def _reduce_4(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 12)
  def _reduce_5(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 13)
  def _reduce_6(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 15)
  def _reduce_7(val, _values, result)
    result = GramNode.new( :TOP_BLOCK,  val[0], val[1] )
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 17)
  def _reduce_8(val, _values, result)
     val[1] ; result = GramNode.new( :DATA_BLOCK, GramNode.new(:ident, val[2]), val[3], GramNode.new( :string, val[5]))
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 19)
  def _reduce_9(val, _values, result)
     result = GramNode.new( :PROC_BLOCK, GramNode.new(:ident, val[1]), val[2], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 21)
  def _reduce_10(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 22)
  def _reduce_11(val, _values, result)
     result = Array.new(1, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 23)
  def _reduce_12(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 25)
  def _reduce_13(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 26)
  def _reduce_14(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 28)
  def _reduce_15(val, _values, result)
     result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 29)
  def _reduce_16(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 31)
  def _reduce_17(val, _values, result)
    result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 32)
  def _reduce_18(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 34)
  def _reduce_19(val, _values, result)
    result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 35)
  def _reduce_20(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 37)
  def _reduce_21(val, _values, result)
     val[0] << val[1]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 38)
  def _reduce_22(val, _values, result)
     result = Array.new(1, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 40)
  def _reduce_23(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 41)
  def _reduce_24(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 43)
  def _reduce_25(val, _values, result)
     result = GramNode.new(:option, val[0], true )
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 45)
  def _reduce_26(val, _values, result)
     result = GramNode.new(:option, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 47)
  def _reduce_27(val, _values, result)
     result = GramNode.new(:num   , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 48)
  def _reduce_28(val, _values, result)
     result = GramNode.new(:sq_string, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 49)
  def _reduce_29(val, _values, result)
     result = GramNode.new(:dq_string, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 50)
  def _reduce_30(val, _values, result)
     result = GramNode.new(:ident , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 52)
  def _reduce_31(val, _values, result)
     val[0] << val[2]; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 53)
  def _reduce_32(val, _values, result)
     result = Array.new(1, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 55)
  def _reduce_33(val, _values, result)
     result = GramNode.new( :proc_stmt , GramNode.new(:ident, val[0]) , val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 57)
  def _reduce_34(val, _values, result)
    result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 58)
  def _reduce_35(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 60)
  def _reduce_36(val, _values, result)
     val[0] << val[1] ; result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 61)
  def _reduce_37(val, _values, result)
     result = Array.new(1, val[0] )
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 63)
  def _reduce_38(val, _values, result)
     result = GramNode.new(:ident , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 64)
  def _reduce_39(val, _values, result)
     result = GramNode.new(:num   , val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 65)
  def _reduce_40(val, _values, result)
     result = GramNode.new(:sq_string, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 66)
  def _reduce_41(val, _values, result)
     result = GramNode.new(:dq_string, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 67)
  def _reduce_42(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 68)
  def _reduce_43(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 69)
  def _reduce_44(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 70)
  def _reduce_45(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 71)
  def _reduce_46(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 72)
  def _reduce_47(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 73)
  def _reduce_48(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 74)
  def _reduce_49(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 75)
  def _reduce_50(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 76)
  def _reduce_51(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 77)
  def _reduce_52(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 78)
  def _reduce_53(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 79)
  def _reduce_54(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 80)
  def _reduce_55(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 81)
  def _reduce_56(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 82)
  def _reduce_57(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 83)
  def _reduce_58(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 84)
  def _reduce_59(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 85)
  def _reduce_60(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 86)
  def _reduce_61(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 87)
  def _reduce_62(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 88)
  def _reduce_63(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 89)
  def _reduce_64(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 90)
  def _reduce_65(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'sts_parse.ry', 91)
  def _reduce_66(val, _values, result)
     result = GramNode.new(:sign, val[0])
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class STSParser


require_relative("sts_gram_node.rb")

module STSParserDriver
  def self.run( tokens )
    parser = STSParser.new

    begin
      gram_tree = parser.parse( tokens )
    rescue Racc::ParseError => e
      puts "Parser error detected"
      puts e.message
      runtime_error = RuntimeError.new( e.message );
      runtime_error.set_backtrace( e.backtrace ); e.set_backtrace([])
      raise runtime_error
    end
  end
end
