#!/usr/bin/env ruby

## Parse argumnet and initialize setting

fork_or_thread = "fork"

if ARGV.include?("--thread")
  fork_or_thread = "thread"
end

## Main

require("statsailr")

reader, writer = IO.pipe

child_service = StatSailr::Service.start( reader , writer, fork_or_thread: fork_or_thread )

prompt = "(^^)v: "
line = ""
print prompt
while true
  line = STDIN.gets()
  if line.nil? # When C-d
    puts "C-d : Parent process finishes. Close pipe."
    writer.close
    break
  elsif line =~ /^!exit/
    puts "!exit : Parent process finishes. Close pipe."
    writer.close
    break
  else
    writer.write line
    print prompt
  end
end

case fork_or_thread
when "fork"
  Process.waitpid(child_service)
when "thread"
  child_service.join()
end
